MysqlPSM:
MysqlDBName:
RedisAddr:
FrontierPSM:
AppID:
AppKey:
EnableIPv6: false
ReconnectTimeout: 60
RoomUserLimit: 1000
VCloudAK:
VCloudSK:
PostProcessingURL:
PostProcessingAK:
PostProcessingSK:
Resolution: 720
VideoDays: 90
RoomDurationMinute: 10
RoomWhiteList:
  -